@host = http://localhost:5256
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoidGVzdCIsImZhbWlseV9uYW1lIjoic2FkIiwianRpIjoiOGRlODYyYjktYmU0Yi00YjFkLTljMDgtY2E4OWI3Y2Y4NTYwIiwic3ViIjoiYmE2YzllZDQtNzI5NC00NDUxLTkyYzQtOTc3NTU0MDA1YTIyIiwiZXhwIjoxNzIxOTE3MDIwLCJpc3MiOiJzaG9wIiwiYXVkIjoiYWxpIn0.Em1y-arEKDCY3LsJcz3gUWjGy4efPNH4ZnZEmGkKybs

Post {{host}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "firstname": "ali",
    "lastname": "adf",
    "email": "as@tdest.com",
    "username": "faasd",
    "password": "123"
}

###

POST  {{host}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "234"
}

###

POST {{host}}/api/dashboard/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "mobile"
}

###

PUT {{host}}/api/dashboard/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Id": "169b70a6-5f15-4c83-a3b7-a5c276fadadc",
    "name": "modified name"
}

###

GET {{host}}/api/dashboard/category
Accept: application/json
Content-Type: application/json

###

Post {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lg",
    "quantity": 10000,
    "price": 1432.00,
    "categoryId": "714A40F0-F431-442F-8AE0-D139023333AE",
    "description": "lorem ipsum"
}


###

Put {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "024378CA-09B1-4B06-B018-8862E5F6FA59",
    "name": "ewr",
    "quantity": 10,
    "price": 84.00,
    "categoryId": "f252b5dc-adc2-48fd-b02a-4651cb505b6b"
}

###

GET {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json

###

DELETE {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "5c4940b5-b147-4066-b76e-d3212e67bf32"
}