@host = http://localhost:5256
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiJiMmRlZWFhYy00ZWY3LTQwODgtYTJhZC03YmQ3ZjhlZDA1YWMiLCJzdWIiOiIyZDZlMmJkYi1lZTJlLTQ4MWYtYTE1Yi03NGYxZTViMjI3N2IiLCJleHAiOjE3Mjg1ODg1NjQsImlzcyI6InNob3AiLCJhdWQiOiJhbGkifQ.G9E-M4oBj0ivSOf5ZPzBbe_enuhPiUFRbQHviWB7vOw
@tokenBuyer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiYWxpIiwiZmFtaWx5X25hbWUiOiJha2JhcmkiLCJqdGkiOiIzZDBjOTk3MS1iYWRiLTQyNTEtYTg2Ni0yZDYyNzc1NjgxOTAiLCJzdWIiOiI0MjQwNjYxNC0xZjkyLTQ3MzAtODJlYy0yZDg1YWIyZmRjNjEiLCJleHAiOjE3MjQ3Njk0MTUsImlzcyI6InNob3AiLCJhdWQiOiJhbGkifQ.L7hk_E7X7VGmZINCD1gZBXb0mYVLX73Oy4J9heB2CEE



Post {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "ali",
    "quantity": 10000,
    "price": 1432.00,
    "categoryId": "0E496697-BB57-4D9E-8686-5E282095F641",
    "description": "lorem ipsum",
    "tagIds": ["083A2E50-6504-44A1-9236-4532167B728C", "1D5EBF49-F392-49B9-897D-9EB0702021FE"]
}


###

Put {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "41A45589-3F6C-4981-AA4F-58F46EC5F11B",
    "name": "modified",
    "quantity": 10,
    "isAvailable": true
}

###

GET {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json

###

DELETE {{host}}/api/dashboard/product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "E49A8506-6771-41A0-B2DF-606FC9AC3421"
}

