@host = http://localhost:5256
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI0N2JkOWJhYS01YjA0LTQ0MmEtOWFiNi1jYWEyNTVmY2I2ODkiLCJzdWIiOiIyZDZlMmJkYi1lZTJlLTQ4MWYtYTE1Yi03NGYxZTViMjI3N2IiLCJleHAiOjE3MjkxMDQwNDUsImlzcyI6InNob3AiLCJhdWQiOiJhbGkifQ.6yXDs-EakUnEEmwdxt3GBZISUz6PIBJxFCY_Ap5lMH0
@tokenBuyer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiYWxpIiwiZmFtaWx5X25hbWUiOiJha2JhcmkiLCJqdGkiOiIzZDBjOTk3MS1iYWRiLTQyNTEtYTg2Ni0yZDYyNzc1NjgxOTAiLCJzdWIiOiI0MjQwNjYxNC0xZjkyLTQ3MzAtODJlYy0yZDg1YWIyZmRjNjEiLCJleHAiOjE3MjQ3Njk0MTUsImlzcyI6InNob3AiLCJhdWQiOiJhbGkifQ.L7hk_E7X7VGmZINCD1gZBXb0mYVLX73Oy4J9heB2CEE


POST {{host}}/api/dashboard/tag
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "soid"
}

###

PUT {{host}}/api/dashboard/tag
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Id": "169b70a6-5f15-4c83-a3b7-a5c276fadadc",
    "name": "modified name"
}

###

GET {{host}}/api/dashboard/tag
Accept: application/json
Content-Type: application/json

###


DELETE {{host}}/api/dashboard/tag
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "categoryId": "08DCD081-3F30-49E4-8919-743D57898C42"
}

